AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  ApplicationName:
    Type: String
    Default: 'defaultappname'
    Description: 'Name of an application'
  DomainName:
    Type: String
    Default: 'defaultdomain'
    Description: 'Name of an application'

Mappings: 

Conditions: 

Resources:
  CFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Join
            - '.'
            - -  'www'
              -  !Ref DomainName
          - !Ref DomainName
        CNAMEs:
          - null
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'GET'
            - 'HEAD'
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad 
          ViewerProtocolPolicy: 'redirect-to-https'
          TargetOriginId: 'S3OriginID'
        Enabled: yes
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt S3WebsiteBucket.WebsiteURL
            Id: S3OriginID
            CustomOriginConfig:
                OriginProtocolPolicy: match-viewer
      Tags:
        - Key: 'project'
          Value: !Ref ApplicationName
  S3WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Join
      - ''
      - -  !Ref ApplicationName
        -  'bucket'
      WebsiteConfiguration: 
        IndexDocument: index.html
      Tags:
        - Key: 'project'
          Value: !Ref ApplicationName
  Route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Join
            - '.'
            - -  'www'
              -  !Ref DomainName
  Route53RSGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Route53HostedZone
      RecordSets: 
      - Name: !Ref DomainName
        ResourceRecords: !GetAtt CFDistribution.DomainName
          - 
        Type: A
      - Name: !Join
            - '.'
            - -  'www'
              -  !Ref DomainName
        ResourceRecords: !GetAtt CFDistribution.DomainName
          - 
        Type: A
Outputs: